config/routes.rb
Joshanderson::Application.routes.draw do
  resources :blogs

  get "homepage/index"

  root :to => 'homepage#index'

  get "homepage/aboutme"

  get "homepage/uvalue"

  get "homepage/technologistgroup"

  get "homepage/projects"

  get "homepage/contactme"

  get "projects/project1"

  get "projects/uvalue"
  
  get "projects/technologistgroup"
  
  get "projects/epitome"
  
  get "projects/stgabriels"

  get "projects/norman"

  get "projects/99designs"

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  attr_accessible :author, :content, :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  # GET /blogs
  http_basic_authenticate_with :name => "frodo", :password => "thering", :except => [:index, :show]

  # GET /blogs.json
  def index
    @title = "Blog"
    @blogs = Blog.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @blogs }
    end
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @title = "Blog"
    @blog = Blog.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @blog }
    end
  end

  # GET /blogs/new
  # GET /blogs/new.json
  def new
    @title= "New Blog Post"
    @blog = Blog.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @blog }
    end
  end

  # GET /blogs/1/edit
  def edit
    @title = "Edit Blog Post"
    @blog = Blog.find(params[:id])
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @title = "Create New Blog Post"
    @blog = Blog.new(params[:blog])

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render json: @blog, status: :created, location: @blog }
      else
        format.html { render action: "new" }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /blogs/1
  # PUT /blogs/1.json
  def update
    @blog = Blog.find(params[:id])

    respond_to do |format|
      if @blog.update_attributes(params[:blog])
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
  end

  def aboutme
    @title = "Learn more about Me"
  end

  def uvalue
    @title = "Uvalue"
  end

  def technologistgroup
    @title = "The Technologist Group"
  end

  def projects
    @title = "View My Projects"
  end

  def contactme
    @title= "Need to Get in Touch with me?"
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

def project1
    @title = "Project 1"
end

def uvalue
    @title = "Uvalue.co"
end
def technologistgroup
    @title = "The Technologist Group"
end
def epitome
    @title = "Epitome of Soul Organization Website"
end
def norman
    @title = "NormanFranklin.com"
end
def stgabriels
    @title = "St Gabriel's Hollis Church Website"
end
def ninetyninedesigns
    @title = "99 Designs Projects"
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content, style: "height:60px;" %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-success btn-large" %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<%= render 'layouts/innerpage' %>

<% @blogs.each do |blog| %>

  <div class="post-area">
    <div style="font-size:25pt; width:80%;position: relative; margin-top: 10px;"><%= blog.title %></div>
    <div style="float:right; width:20%; margin-top: -10px; position: relative;"><%= blog.author %></div><br/>
    <%= blog.content %></br></br>
    <p>
    <%= link_to 'Read More', blog, :class => "btn btn-success btn-xs" %>
    <!--<%= link_to 'Edit', edit_blog_path(blog), :class => "btn btn-success btn-xs" %>
    <%= link_to 'Destroy', blog, :class => "btn btn-success btn-xs",  method: :delete, data: { confirm: 'Are you sure?'} %>-->
    </p>
  </div>

<% end %>


<br />

<%= link_to 'New Blog', new_blog_path,  class: "btn btn-success btn-large" %>

app/views/blogs/new.html.erb
<%= render 'layouts/innerpage' %>
		<%= render 'form' %>

		<%= link_to 'Back', blogs_path %>
		
		</div>
</div>

app/views/blogs/show.html.erb
<%= render 'layouts/innerpage' %>

<p id="notice"><%= notice %></p>

<div class="post-area">
<p>
  <h1><%= @blog.title %></h1>
</p>

<p>
  <b>Author:</b>
  <%= @blog.author %>
</p>

<p>
  <b>Date Added:</b>
  <%= @blog.created_at %>
</p>
 
<p>
  <b>Content:</b>
  <%= @blog.content %>
</p>


<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

</div>

app/views/homepage/aboutme.html.erb
<%= render 'layouts/innerpage' %>


<h3>Joshua Anderson: Technology Enthusiast</h3>
<p>
Since beginning my job search I have targeted employment opportunities in Front End Web Development and Digital Marketing. My experiences since graduating with a Bachelors Degree from Syracuse University in 2011 have been quite unconventional in that the opportunities I was given allowed me to flourish in numerous roles and attain a high level of responsibility and personal accountability early on in my career. I have already worked for two Fortune 500 companies as well as had my fair share of entrepreneurial experiences, which has allowed me to reach levels of individual success as well as some depth of failure. I mention my failures because I truly believe as a leader and as someone still early in their career; I have learned so much more from my defeats then I have from my victories.
</p>
<p>
No matter what tasks, roles, or responsibilities I have taken on in my career, I have always performed them with great quality and leadership. I have led teams of talented individuals, given professional presentations to investors and audiences of hundreds of people, and closed consulting deals worth thousands of dollars all while pursuing (and completing) a Masters Degree in Information Management. My Master's Degree was afforded to me through a Kauffman Entrepreneurial Fellowship and scholarships from Syracuse University as an acknowledgement of the leadership qualities they believe I have and will continue to show in the tech industry.
</p>
<p>
Over the past 5 years I've grown my technical ability for: Ruby on Rails, PHP, HTML, CSS, and JQuery so that I can better interface with developers and take on that responsibility. While in graduate school I was able to sharpen my expertise by building a marketplace startup business. I also possess hands on experience with Search Engine Optimization, building Ecommerce based products, and have been designing and building websites for the past 10 years. 
</p>

app/views/homepage/contactme.html.erb
<%= render 'layouts/innerpage' %>

<p>Send Me and email using this email link:
<a href="mailto:joshua.aaron.anderson@gmail.com" target="_top">
Send Mail</a></p>

<%= render 'layouts/mailchimp' %>

app/views/homepage/index.html.erb
<style>
body {
background-color: #34383D;
}
</style>

<!--<div class="top-green"></div>-->
<!--<div style="text-shadow: 0 -1px 0 rgba(0,0,0,.15);
background-color: #98c62c;
border-color: #98c62c;
box-shadow: 0 1px 0 rgba(255,255,255,.1);width: 100%; height:70px; left:0; right:0; position:absolute;"></div>-->
<!--<div id="panning" class="panning"></div>-->
<div class="front-bg">

<div class="icon-links">
	<%= link_to image_tag("twitter.png", :alt => "JoshAndersonInc", :class => 'icon-pad'),  "https://twitter.com/JoshAndersonInc" %>
	<%= link_to image_tag("github.png", :alt => "JoshAnderson5", :class => 'icon-pad'),  "https://github.com/JoshAnderson5" %>
	<%= link_to image_tag("dribbble.png", :alt => "JoshAndersonInc", :class => 'icon-pad'),  "https://dribbble.com/JoshAndersonInc" %>
</div>

	<div class="container">
		<div class="fullname">JOSH ANDERSON</div>
	    <div class="email">joshua.aaron.anderson@gmail.com</div> 
	       <ul style="text-align:center; margin: 20px 0px 0px 265px;"> 
	            
	            <div>
	            <li class="masthead"><%= link_to "About Me", homepage_aboutme_path, class: "green-links"  %></li>
	            <!--<li class="masthead" ><%= link_to "Projects", homepage_projects_path, class: "green-links"  %></li> 
	            <li class="masthead"><%= link_to "Resume", "https://www.dropbox.com/s/deija9f7twmrdck/JoshAndersonResume%202014.doc", class: "green-links"  %></li>
	            <li class="masthead" ><%= link_to "Blog", "http://technologistgroup.com/blog/", class: "green-links"  %></li>
	            <li class="masthead" ><%= link_to "Contact Me", homepage_contactme_path, class: "green-links" %></li>-->    
	                    
	            </div>
	          </ul>
	</div> 
</div>
<div class="container">
		
</div>

app/views/homepage/projects.html.erb
<%= render 'layouts/innerpage' %>

<span class="back-link" style="margin-top: -48px;"><a href="https://github.com/JoshAnderson5">View My Github Profile</a></span>

<div class="icon-project">
<%= link_to image_tag("browser256.png", :alt => "Website Icon", :class => 'frame'),  "" %>
</div>

<div class="list-group">
      <a href="#" class="list-group-item active">
        <h3 class="list-group-item-heading" style="text-align:center;">Recent Projects</h3>
        <p class="list-group-item-text" style="text-align:center;">Below is a list of some of the projects I've worked on over the last few years. Hopefully it gives you a better insight into some of my capabilities.</p>
      </a>

      <a href="/projects/uvalue" class="list-group-item">
        <h4 class="list-group-item-heading" style="text-align:center;">Uvalue</h4>
        <p class="list-group-item-text" style="text-align:center;">Wireframes, Photoshop, Php, Linux, Html, CSS, Javascript, JQuery</p>
      </a>
      <a href="/projects/technologistgroup" class="list-group-item">
        <h4 class="list-group-item-heading" style="text-align:center;">The Technologist Group</h4>
        <p class="list-group-item-text" style="text-align:center;">Wordpress, Php, Html, CSS, Responsive Design, JQuery</p>
      </a>
      <a href="/projects/epitome" class="list-group-item">
        <h4 class="list-group-item-heading" style="text-align:center;">Epitome of Soul</h4>
        <p class="list-group-item-text" style="text-align:center;">Wordpress, Php, Html, CSS, JQuery</p>
      </a>
      <a href="/projects/stgabriels" class="list-group-item">
        <h4 class="list-group-item-heading" style="text-align:center;">St. Gabriel's Church Website</h4>
        <p class="list-group-item-text" style="text-align:center;">Photoshop, Wordpress, Php, Html, CSS, Responsive Design</p>
      </a>
      <a href="/projects/norman" class="list-group-item">
        <h4 class="list-group-item-heading" style="text-align:center;">NormanFranklin.com</h4>
        <p class="list-group-item-text" style="text-align:center;">Wordpress, Php, Html, CSS, Javascript</p>
      </a>
      <a href="/projects/ninetyninedesigns" class="list-group-item">
        <h4 class="list-group-item-heading" style="text-align:center;">Design Work from 99Designs</h4>
        <p class="list-group-item-text" style="text-align:center;">Photoshop, Heavy Iteration Based on Client Feedback</p>
      </a>
 </div>

app/views/homepage/technologistgroup.html.erb
<%= render 'layouts/innerpage' %>

<h1>Website Design & Consulting</h1>
<p></p>

<div class="tgroup">
</div>

app/views/homepage/uvalue.html.erb
<%= render 'layouts/innerpage' %>

<h1>Uvalue.co: Making the Pivot</h1>

<div class="white-area">
<p>Uvalue is undergoing a transition phase. If you go to www.uvalue.co you will see the first version of Uvalue which is still live a college community marketplace. I'm currently working to make the application more expansive and impactful within the ecommerce vertical. A preview for what is planned for the next version can be found in the slideshare presentation listed below.</p>


<iframe src="http://www.slideshare.net/slideshow/embed_code/29474322" width="427" height="356" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" style="border:1px solid #CCC;border-width:1px 1px 0;margin-bottom:5px" allowfullscreen> </iframe> <div style="margin-bottom:5px"> <strong> <a href="https://www.slideshare.net/joshuaaaronanderson/uvalue-ruby-demoday2013" title="Uvalue ruby demoday2013" target="_blank">Uvalue ruby demoday2013</a> </strong> from <strong><a href="http://www.slideshare.net/joshuaaaronanderson" target="_blank">Joshua Anderson</a></strong> </div>

</div>

app/views/layouts/_innerpage.html.erb
<div class="left-inner">

<ul class="nav-white"> 
				<div class="profile-link"><%= link_to "Joshua Anderson", root_path %></div>
				<div class="profile">
					
				</div>
	                 <span class="nav">
	                 <!--<li class="masthead" style="margin-top: -10px;"><h1>JoshAnderson.co</h1></li>-->
	                 <li><%= link_to "About Me", homepage_aboutme_path, class: "sidebar-links"  %></li>
	 				 <li><%= link_to "Resume", "https://www.dropbox.com/s/f7zytq7s963ihkw/JAndersonResume2014.pdf", class: "sidebar-links"  %></li>
	                 <li><%= link_to "Projects", homepage_projects_path, class: "sidebar-links"  %></li>
	                 <li><%= link_to "My Blog", "http://technologistgroup.com/blog/", class: "sidebar-links"  %></li>
	                 <li><%= link_to "Contact Me", homepage_contactme_path, class: "sidebar-links" %></li>
	                 </span>
	          </ul>
</div>

<div class="right-inner">
	<div class="hero-wrap">
		<br/>
		<span class="heading-title"><%= @title %></span>
	</div>
		<div class="page-layout">


app/views/layouts/_mailchimp.html.erb
	<!-- Begin MailChimp Signup Form -->
	<link href="//cdn-images.mailchimp.com/embedcode/classic-081711.css" rel="stylesheet" type="text/css">
	<style type="text/css">
		#mc_embed_signup{clear:left; font:14px Helvetica,Arial,sans-serif; }
		/* Add your own MailChimp form style overrides in your site stylesheet or in this style block.
		   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
	</style>
	<div id="mc_embed_signup">
	<form action="http://uvalue.us2.list-manage.com/subscribe/post?u=ef032114e95da6dae18aad600&amp;id=3315db89c1" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
		<h2 style="margin: 1px 0;">Subscribe to Josh's mailing list</h2>
	<div class="indicates-required"><span class="asterisk">*</span> indicates required</div>
	<div class="mc-field-group">
		<label for="mce-EMAIL">Email Address  <span class="asterisk">*</span>
	</label>
		<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL" style="margin-left:-20px">
	</div>
	<div class="mc-field-group">
		<label for="mce-FNAME">First Name </label>
		<input type="text" value="" name="FNAME" class="" id="mce-FNAME">
	</div>
	<div class="mc-field-group">
		<label for="mce-LNAME">Last Name </label>
		<input type="text" value="" name="LNAME" class="" id="mce-LNAME">
	</div>
	<div class="mc-field-group input-group">
	    <strong>Email Format </strong>
	    <ul><li><input type="radio" value="html" name="EMAILTYPE" id="mce-EMAILTYPE-0"><label for="mce-EMAILTYPE-0">html</label></li>
	<li><input type="radio" value="text" name="EMAILTYPE" id="mce-EMAILTYPE-1"><label for="mce-EMAILTYPE-1">text</label></li>
	</ul>
	</div>
		<div id="mce-responses" class="clear">
			<div class="response" id="mce-error-response" style="display:none"></div>
			<div class="response" id="mce-success-response" style="display:none"></div>
		</div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
	    <div style="position: absolute; left: -5000px;"><input type="text" name="b_ef032114e95da6dae18aad600_3315db89c1" value=""></div>
		<div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
	</form>
	</div>

	<!--End mc_embed_signup-->

app/views/layouts/_navigation.html.erb
<div style="text-shadow: 0 -1px 0 rgba(0,0,0,.15);
background-color: #98c62c;
border-color: #98c62c;
box-shadow: 0 1px 0 rgba(255,255,255,.1);width: 100%; height:70px; left:0; right:0; position:absolute;"></div>

	<div class="container">
		<div style="float:left">
		
		</div>

			  <ul class="nav-white"> 
	                 <span class="nav">
	                 <!--<li class="masthead" style="margin-top: -10px;"><h1>JoshAnderson.co</h1></li>-->
	                 <li class="masthead"><%= link_to "About Me", homepage_aboutme_path, class: "green-links" %></li>
	                 <!--<li class="masthead"><%= link_to "Uvalue", homepage_uvalue_path, class: "btn btn-outline-inverse btn-lg"  %></li>-->
	                 <!--<li class="masthead"><%= link_to "Technologist Group", homepage_technologistgroup_path, class: "btn btn-outline-inverse btn-lg"  %></li>-->
	                 <li class="masthead"><%= link_to "Resume", "https://www.dropbox.com/s/deija9f7twmrdck/JoshAndersonResume%202014.doc", class: "btn btn-outline-inverse btn-lg"  %></li>
	                 <li class="masthead" ><%= link_to "Active Projects", homepage_projects_path, class: "btn btn-outline-inverse btn-lg"  %></li>
	                 <li class="masthead" ><%= link_to "Blog", blogs_path, class: "btn btn-outline-inverse btn-lg"  %></li>
	                 <li class="masthead" ><%= link_to "Contact Me", homepage_contactme_path, class: "btn btn-outline-inverse btn-lg" %></li>
	                    </span>
	          </ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Joshanderson</title>
  <link href='http://fonts.googleapis.com/css?family=Oswald:400,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>